name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev", "feature/*"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read #those permissions are required to run the codeql analysis
  actions: read
  security-events: write

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      solutionName: Microsoft.Kiota.sln
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
      - name: Check formatting
        run: dotnet format ${{ env.solutionName }} --verify-no-changes
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore /p:UseSharedCompilation=false
      - name: Test for net462
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal --framework net462
      - name: Test for net9.0 and collect coverage
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover --framework net9.0
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
